build:
  cuda_version: "12.9"
  python_version: "3.10"
  system_packages:
    - "git"
  python_packages:
    - "torch"
  run:
    - "git clone https://huggingface.co/spaces/dangthr/Hunyuan3D-Part && cd Hunyuan3D-Part && pip install packaging setuptools spaces wheel && pip install --no-cache-dir -r requirements.txt"
